export const LOCAL_TEMPLATE_THUMBNAILS: Record<string, string> = {
  modern: "/template-thumbnails/modern.png",
  bold: "/template-thumbnails/bold.png",
  dynamic: "/template-thumbnails/dynamic.png",
  horizon: "/template-thumbnails/horizon.png",
  vibrant: "/template-thumbnails/vibrant.png",
  spotlight: "/template-thumbnails/spotlight.png",
  standard: "/template-thumbnails/standard.png",
  corporate: "/template-thumbnails/corporate.png",
  executive: "/template-thumbnails/executive.png",
  functional: "/template-thumbnails/functional.png",
  simple: "/template-thumbnails/simple.png",
  academic: "/template-thumbnails/academic.png",
  classic: "/template-thumbnails/classic.png",
  minimal: "/template-thumbnails/minimal.png",
  air: "/template-thumbnails/air.png",
  focus: "/template-thumbnails/focus.png",
  compact: "/template-thumbnails/compact.png",
  tech: "/template-thumbnails/tech.png",
  startup: "/template-thumbnails/startup.png",
  creative: "/template-thumbnails/creative.png",
  narrative: "/template-thumbnails/narrative.png",
  journey: "/template-thumbnails/journey.png",
}

